SELECT a.CAR_ID, ROUND(AVG(DATEDIFF(a.END_DATE, a.START_DATE) + 1), 1) AS AVERAGE_DURACTION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY a
GROUP BY a.CAR_ID 
HAVING AVERAGE_DURACTION >= 7
ORDER BY AVERAGE_DURACTION DESC, a.CAR_ID DESC