SELECT A.CAR_ID
  FROM CAR_RENTAL_COMPANY_CAR AS A
 INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS B
    ON A.CAR_ID = B.CAR_ID
 WHERE A.CAR_TYPE = '세단'
   AND B.START_DATE BETWEEN '2022-10-01' AND '2022-10-31'
 GROUP BY A.CAR_ID
 ORDER BY A.CAR_ID DESC