-- 코드를 작성해주세요
SELECT SUM(C.SCORE) AS SCORE, B.EMP_NO, B.EMP_NAME, B.POSITION, B.EMAIL
  FROM HR_EMPLOYEES AS B
  JOIN HR_DEPARTMENT AS A
    ON B.DEPT_ID = A.DEPT_ID
  JOIN HR_GRADE AS C
    ON B.EMP_NO = C.EMP_NO
 WHERE C.YEAR = 2022
 GROUP BY B.EMP_NO
 ORDER BY SCORE DESC
 LIMIT 1